# database info
dsn = "root:root@tcp(127.0.0.1:3306)/beego-test"

# if you want to auto create FE code, you should set the proType=ant4 and path.ant="***"
proType = "ant4"

## field information of example table
[models.example]
    names = ["row1","row2","row3","row4"]
    orms = ["int","string","text","datetime"]
    comments = ["字段一","字段二","字段三","字段四"]

[path]
    beego =  "."
#    ant  = "./ant/src/pages"
